version: '3.8'

services:
  mariadb1:
    image: mariadb:11.1
    restart: always
    container_name: maria
    environment:
      MARIADB_ROOT_PASSWORD: my-secret-pw
      MARIADB_USER: my_user 
      MARIADB_PASSWORD: my_password
      MARIADB_DATABASE: swidnica
    volumes:
      - /srv/Swidnica/Zostan_w_Swidnicy/software/services/db/init.sql:/docker-entrypoint-initdb.d/init.sql # sciezka do pliku inicjujacego baze danych
      - /tmp/db1:/var/lib/mysql
    healthcheck:
      test: mariadb -u my_user -pmy_password -h 127.0.0.1 
      interval: 5s 
      timeout: 2s
      retries: 50
      start_period: 10s
      start_interval: 5s

  api_gateway:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    restart: always
    ports:
      - 9020:8080
    depends_on:
      mariadb1:
        condition: service_healthy

  db_driver:
    build:
      context: ./db_driver
      dockerfile: Dockerfile
    restart: always
    ports:
      - 9041:8080
    depends_on:
      mariadb1:
        condition: service_healthy

  employee:
    build:
      context: ./employee
      dockerfile: Dockerfile
    restart: always
    ports:
      - 9032:8080
    depends_on:
      mariadb1:
        condition: service_healthy

  employer:
    build:
      context: ./employer
      dockerfile: Dockerfile
    restart: always
    ports:
      - 9033:8080
    depends_on:
      mariadb1:
        condition: service_healthy
        
  identity:
    build:
      context: ./identity
      dockerfile: Dockerfile
    restart: always
    ports:
      - 9031:8080
    depends_on:
      mariadb1:
        condition: service_healthy

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:5173
      - 443:5173
    depends_on:
      mariadb1:
        condition: service_healthy