import os

# Server
HOST : str = "0.0.0.0"
PORT : int = 8080

# Database
DATABASE_HOST = "maria"
DATABASE_PORT = 9050

DATABASE_USER = os.getenv("MARIADB_USER")
DATABASE_PASSWORD = os.getenv("MARIADB_PASSWORD")
DATABASE_NAME = os.getenv("MARIADB_DATABASE")

DATABASE_URL = f"mariadb://{DATABASE_USER}:{DATABASE_PASSWORD}@{DATABASE_HOST}:{DATABASE_PORT}/{DATABASE_NAME}"